name: Update Documentation

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Send POST request
        run: |
          curl -X POST https://api.manifest-hq.com/openai-update-platform-assistant \
          -H "Content-Type: application/json" \
